FROM python:3.8.6-slim-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN pip install --no-cache-dir pytest flake8

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
